### ISSUE TITLE
Unspecified dependency: ggsci

### ISSUE THREAD

**Issue by SciLiciumTheo** [cafferychen777/MicrobiomeStat#10]
I installed MicrobiomeStat through `devtools`.

The example for function `generate_taxa_barplot_pair` 
```
 generate_taxa_barplot_pair(
  data.obj = peerj32.obj,
  subject.var = "subject",
  time.var = "time",
  group.var = "group",
  strata.var = NULL,
  feature.level = "Family",
  feature.dat.type = c("count"),
  feature.number = 8,
  base.size = 10,
  theme.choice = "bw",
  custom.theme = NULL,
  palette = ggsci::pal_npg()(9),
  pdf = TRUE,
  file.ann = NULL,
  pdf.wid = 11,
  pdf.hei = 8.5
)
```
failed with the following error:
`Error in loadNamespace(x) : there is no package called ‘ggsci’`

Installing `ggsci` solved the issue.

I suggest that you add `ggsci` to the list of dependencies on https://www.microbiomestat.wiki/setting-up-microbiomestat-installation-and-data-preparation/kick-start-your-journey-the-microbiomestat-installation-guide

**Comment by cafferychen777** [comment]
Hello @SciLiciumTheo ,

Thank you for bringing this issue to our attention. We appreciate your interest in using the MicrobiomeStat package.

In regard to your suggestion about adding 'ggsci' to the list of dependencies, our team prioritizes minimizing the number of package dependencies to maintain the stability of MicrobiomeStat. It is possible to run the function without the 'ggsci' package by setting the `palette` parameter to NULL. Consequently, we have opted to remove the use of 'ggsci' from the installation guide on our wiki.

Thank you again for your valuable feedback. We're always looking to improve the package and your input helps us do just that.

Best regards,
Chen YANG

**Comment by SciLiciumTheo** [comment]
Thanks for the update!

I totally understand your reasons, it makes sense to try to keep things as tidy as possible.

All the best,
Theo
