### ISSUE TITLE
All samples were excluded after subsetting data

### ISSUE THREAD

**Issue by Bio2406839** [cafferychen777/MicrobiomeStat#38]
Hi I'm new to using this great tool. I have a small dataset of 20 samples. Including two groups and 10 timepoints for each group.  I was trying to use the generate_alpha_test_long function to do alpha diversity analysis. I also made sure to make the Subject, Group, and Timepoint variables a factor.

my metadata:
<img width="300" alt="image" src="https://github.com/cafferychen777/MicrobiomeStat/assets/162768443/061fdd58-5572-4110-9880-6d0d563e1aa8">

The code:

MicrobiomeData <- list(
  feature.tab = feature.tab,
  meta.dat = meta.dat,
  feature.ann = feature.ann,
  tree = tree
)

MicrobiomeData$meta.dat$Timepoint <- factor(as.factor(MicrobiomeData$meta.dat$Timepoint), levels = c("T1", "T2", "T3", "T4","T5","T6", "T7", "T8", "T9", "T10"))

MicrobiomeData$feature.tab <- as.data.frame(MicrobiomeData$feature.tab) %>%
  as.matrix()

MicrobiomeData$meta.dat <- as.matrix(MicrobiomeData$meta.dat) %>%
  as.data.frame()

MicrobiomeData$feature.ann <- MicrobiomeData$feature.ann %>%
  as.data.frame() %>%
  as.matrix()

alpha_test_results <- generate_alpha_test_long(
  data.obj = MicrobiomeData,
  alpha.name = c("shannon", "simpson", "observed_species", "chao1", "ace", "pielou"),
  time.var = "Timepoint",
  t0.level = unique(MicrobiomeData$meta.dat$Timepoint)[1],
  ts.levels = unique(MicrobiomeData$meta.dat$Timepoint)[-1],
  group.var = "Group"
)

But I got these explanations and an empty list at the end:

Rule 1 passed: data.obj is a list.
Rule 2 passed: meta.dat is a data.frame.
Rule 3 passed: The row names of feature.tab match the row names of feature.ann.
Rule 4 passed: The order of rows in meta.dat has been adjusted to match feature.tab.
Rule 5 passed: feature.tab is a matrix.
Rule 6 passed: feature.ann is a matrix.
Please note: The data components should follow base R data.frame and matrix structures, not phyloseq's formal class.
Validation passed.
Note: Passing validation does not guarantee the absence of all data issues. Further data exploration may be needed.
Diversity analysis needs rarefaction! Call 'mStat_rarefy_data' to rarefy the data!
No depth specified, using the smallest column sum:  332393
Removed  1  rows from the OTU table and feature annotations due to all-zero counts after rarefication. The removed rows are:  1547 .
Data has been subsetted based on the provided samIDs.
Updated metadata to match the subsetted data.
The following samples were excluded: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
Updated feature table to match the subsetted data.
Updated feature annotation to match the subsetted data.
Data subsetting complete. Returning updated data object.
Calculating shannon diversity...
Calculating simpson diversity...
Calculating observed_species diversity...
Calculating chao1 diversity...
Calculating ace diversity...
Calculating pielou diversity...
Diversity calculations complete.

I'm not sure why all samples are excluded. Is samID the same as subject or individual samples' IDs? Could you please explain the step in which some samples are excluded.

Thanks,

**Comment by cafferychen777** [comment]
Hi @Bio2406839,

Thank you for reaching out and using MicrobiomeStat. It's great to hear that you're finding the tool useful.

Regarding your issue with all samples being excluded, it's indeed strange. One possible reason might be the conversion of `time.var` to a factor. In some cases, this conversion might lead to unexpected behaviors in the subsetting process. I suggest trying the analysis again without converting the `Timepoint` variable to a factor:

```R
MicrobiomeData$meta.dat$Timepoint <- as.character(MicrobiomeData$meta.dat$Timepoint)
```

If the problem persists, it would be helpful if you could share a subset of your data with me. This will allow me to investigate the issue further and identify any potential bugs in the package. You can share the data by uploading it to a file-sharing service and providing the link, or by attaching it to an email.

Please let me know how it goes, and feel free to reach out if you have any further questions or issues.

Best regards,

Chen YANG

**Comment by Bio2406839** [comment]
Thank you so much @cafferychen777 for getting back to me this fast. Please find my test data and the code that produces the error I get.

folder link: https://www.dropbox.com/scl/fo/k9kt2rdde5ovt6bpr0cuw/h?rlkey=vfor2msr07ed7kcaclp5zk8y8&dl=0 

messages after running the generate_alpha_test_long:
Rule 1 passed: data.obj is a list.
Rule 2 passed: meta.dat is a data.frame.
Rule 3 passed: The row names of feature.tab match the row names of feature.ann.
Rule 4 passed: The order of rows in meta.dat has been adjusted to match feature.tab.
Rule 5 passed: feature.tab is a matrix.
Rule 6 passed: feature.ann is a matrix.
Please note: The data components should follow base R data.frame and matrix structures, not phyloseq's formal class.
Validation passed.
Note: Passing validation does not guarantee the absence of all data issues. Further data exploration may be needed.
Diversity analysis needs rarefaction! Call 'mStat_rarefy_data' to rarefy the data!
No depth specified, using the smallest column sum:  301714
Data has been subsetted based on the provided samIDs.
Updated metadata to match the subsetted data.
The following samples were excluded: 1, 2, 3, 4, 5, 6
Updated feature table to match the subsetted data.
Updated feature annotation to match the subsetted data.
Data subsetting complete. Returning updated data object.
Calculating shannon diversity...
Calculating simpson diversity...
Calculating observed_species diversity...
Calculating chao1 diversity...
Calculating ace diversity...
Calculating pielou diversity...
Diversity calculations complete.
Data has been subsetted based on the provided condition.
Updated metadata to match the subsetted data.
The following samples were excluded: 
Updated feature table to match the subsetted data.
Updated feature annotation to match the subsetted data.
Data subsetting complete. Returning updated data object.
Data has been subsetted based on the provided condition.
Updated metadata to match the subsetted data.
The following samples were excluded: 
Error in `dplyr::select()`:
! Can't select within an unnamed vector.
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
In vegan::rrarefy(t(otu_tab), sample = depth) :
  function should be used for observed counts, but smallest count is 15

**Comment by cafferychen777** [comment]
Hello @Bio2406839,

Thank you for reaching out and using MicrobiomeStat. I appreciate your detailed explanation of the issue you're encountering.

First, I suggest adjusting the data import as follows:

```R
Feature.tab <- read.csv("/Users/apple/Downloads/test_folder/feature.tab.csv", row.names = 1)
Meta.dat <- read.csv("/Users/apple/Downloads/test_folder/meta.dat.csv", row.names = 1)
Feature.ann <- read.csv("/Users/apple/Downloads/test_folder/feature.ann.csv", row.names = 1)

# Combine into MicrobiomeStat Object
MicrobiomeData <- list(
  feature.tab = as.matrix(Feature.tab),
  meta.dat = Meta.dat,
  feature.ann = as.matrix(Feature.ann)
)
```

Secondly, regarding the inability to run `generate_alpha_test_long`, it appears to be a statistical issue due to the small size of your sample. For example, if your metadata looks like this:

```
MicrobiomeData$meta.dat
          Date Group Timepoint
S1  2024-01-12    g1        T1
S2  2024-01-13    g1        T2
S3  2024-01-14    g1        T3
S11 2024-01-12    g2        T1
S12 2024-01-13    g2        T2
S13 2024-01-14    g2        T3
```

For the functions `generate_alpha_test_long`, `generate_beta_test_long`, and `generate_taxa_test_long`, they essentially subset the data for each time point and perform differential abundance analysis. When you have only two samples per time point, with one sample per group, it may be statistically infeasible to perform the analysis. This issue is not specific to the MicrobiomeStat package but rather a limitation in the statistical approach given the small sample size.

I hope this helps clarify the situation. Please let me know if you have any further questions or if there's anything else I can assist you with.

Best regards,

Chen YANG

**Comment by Bio2406839** [comment]
Thanks for looking into it.
