### ISSUE TITLE
Duplicate records used in the linear model within the "generate_beta_change_test_pair" function

### ISSUE THREAD

**Issue by jstobo** [cafferychen777/MicrobiomeStat#39]
Dear MicrobiomeStat team, 

Thank you for developing this package and the examples, very useful! 

**Describe the Bug**
Prior to my colleague discovering your package, we were analysing paired microbiome data. The approach we took to the comparison of groups for beta diversity was very similar to your "generate_beta_change_test_pair" function. 

After discovering your package, we compared results and noticed some discrepancies. Looking at your function source code, it looks like the issue might be caused by the left join on line 132. It looks like this attempts to identify distinct metadata records for each subject (1 per subject) after excluding "time.var". However, without also excluding the "sample" variable created earlier, this retains records for both timepoints per subject. So the number of records when subsequently fitting the linear model is double what it should be. 

**Reproducible Example**

```r
### Load peerj32.obj data ###
library(microbiome)
library(MicrobiomeStat)
library(dplyr)
data(peerj32.obj)
data.obj <- peerj32.obj

### Define variables required in the "generate_beta_change_test_pair" function ###
time.var = "time"
subject.var = "subject"
group.var = "group"
adj.vars = c("sex")
change.base = "1"
dist.name = "BC"

### Run selected parts of the "generate_beta_change_test_pair" function code ###
dist.obj <-
  mStat_calculate_beta_diversity(data.obj = data.obj, dist.name = dist.name)
metadata <- data.obj$meta.dat %>% dplyr::select(all_of(c(subject.var,group.var,time.var, adj.vars))) %>% rownames_to_column("sample")

change.after <-
  unique(metadata %>% dplyr::select(all_of(c(time.var))))[unique(metadata %>% dplyr::select(all_of(c(time.var)))) != change.base]

dist.df <- as.matrix(dist.obj[[dist.name]]) %>%
  as.data.frame() %>%
  rownames_to_column("sample")

# The following has 1 row per subject, 22 rows total
long.df <- dist.df %>%
  tidyr::gather(key = "sample2", value = "distance", -sample) %>%
  dplyr::left_join(metadata, by = "sample") %>%
  dplyr::left_join(metadata, by = c("sample2" = "sample"), suffix = c(".subject", ".sample")) %>%
  filter(!!sym(paste0(subject.var, ".subject")) == !!sym(paste0(subject.var, ".sample"))) %>%
  dplyr::group_by(!!sym(paste0(subject.var, ".subject"))) %>%
  filter(!!sym(paste0(time.var,".sample")) == change.base) %>%
  filter(!!sym(paste0(time.var,".subject")) != !!sym(paste0(time.var,".sample"))) %>%
  dplyr::ungroup() %>%
  dplyr::select(!!sym(paste0(subject.var, ".subject")), !!sym(paste0(time.var, ".subject")), distance) %>%
  dplyr::rename(!!sym(subject.var) := !!sym(paste0(subject.var, ".subject")), !!sym(time.var) := !!sym(paste0(time.var, ".subject")))
dim(long.df) 

# Running the current code (line 132 of source code), this now contains 2 rows per subject, 44 rows total
long.df <- long.df %>% dplyr::left_join(metadata %>% dplyr::select(-any_of(c(time.var))) %>% dplyr::distinct(), by = subject.var)
dim(long.df)
head(long.df)
```

**Expected Behavior**
Using your "peerj32.obj" dataset, I believe "long.df" should have 22 rows, 1 per subject. 

**Actual Behavior**
Because the variable "sample" is not excluded when selecting unique records, "long.df" has 44 rows, 2 per subject (1 per timepoint per subject). 
![Screenshot (14)](https://github.com/cafferychen777/MicrobiomeStat/assets/164208705/8af3cbda-08d7-49fb-aae8-45dc3d599607)

**Environment Information:**

 - Operating System: Windows 10 Education (version 22H2)
 - R Version: 4.2.1
 - Package Version: microbiome 1.23.1; phyloseq 1.42.0; ggplot2 3.4.3; rlang 1.1.1; tibble 3.2.1; MicrobiomeStat 1.1.3; dplyr 1.1.2

**Attempted Solutions**
I think modifying line 132 as follows should correct this: 
```r
long.df <- long.df %>% dplyr::left_join(metadata %>% dplyr::select(-any_of(c("sample",paste(time.var)))) %>% dplyr::distinct(), by = subject.var)
```
![Screenshot (15)](https://github.com/cafferychen777/MicrobiomeStat/assets/164208705/e7311685-99ee-4a97-a9d5-dc730302fa84)

One further issue for the specific example we were working on was that we had covariates that changed for subjects between baseline and the post-baseline visit. So to ensure we only used the baseline covariates for adjustment, we changed line 132 to the following: 
```r
long.df <- long.df %>% dplyr::left_join(metadata %>% dplyr::filter(!!sym(time.var)  == change.base) %>% dplyr::select(-any_of(c("sample",paste(time.var)))), by = subject.var)
```

Could you please have a look and see if this is indeed an issue, and see if either of the suggested solutions above correct this? 
If it is an issue, I'm not sure if there is a similar problem in any other functions - this is the only one I have come across. 

Many thanks! 

Jamie

**Comment by cafferychen777** [comment]
Dear Jamie,

Thank you so much for bringing this to our attention and for your detailed analysis of the issue with the `generate_beta_change_test_pair` function in MicrobiomeStat. You are absolutely right; the code does have a problem where the left join operation in line 132 inadvertently retains records for both timepoints per subject, leading to a doubling of records when fitting the linear model.

I appreciate your suggested solution of modifying line 132 to exclude both the "sample" and "time.var" variables when selecting distinct records. This change should indeed correct the issue and ensure that `long.df` has the correct number of rows, with one row per subject. I have implemented this fix in the package.

Your further suggestion of filtering the metadata to use only baseline covariates for adjustment is also very insightful and could be beneficial for cases where covariates change between baseline and post-baseline visits. I will consider incorporating this into the function or providing an option for users to specify this behavior.

Once again, thank you for your valuable contribution to improving MicrobiomeStat. Please feel free to reach out if you have any more questions or suggestions.

Best regards,
Chen YANG

**Comment by jstobo** [comment]
Thank you for looking into this and fixing so quickly, it is much appreciated. 

It may only be an issue for our example, but it might be useful to note somewhere in the documentation that only baseline covariates should be used in the metadata, as only the second suggested fix above would have worked in our situation - we would still end up with 2 records for some subjects, because "distinct" would retain records where any covariate values changed between the baseline and follow-up visits for a subject. 

Also, credit has to go to my colleague Daniela, as it was her who spotted there was an issue with this function. 

Best wishes!

Jamie

**Comment by cafferychen777** [comment]
Dear Jamie,

Thank you for your feedback. You are correct that our current implementation primarily supports scenarios where covariates remain constant. We are actively developing new statistical methods to accommodate situations where covariates may change between baseline and follow-up visits. I will make sure to clarify this in the documentation.

Also, a special thanks to Daniela for identifying this issue. Her keen observation is greatly appreciated.

Best regards,
Chen YANG

**Comment by jstobo** [comment]
Many thanks Chen. Looking forward to seeing your future developments! 

Best wishes! 

Jamie
