### ISSUE TITLE
Error installing from github

### ISSUE THREAD

**Issue by fredoowarren** [cafferychen777/MicrobiomeStat#41]
Hi,

I have been trying to install the MetagenomStat package in rstudio and keep coming accross the following error:

> devtools::install_github("cafferychen777/MicrobiomeStat")
Downloading GitHub repo cafferychen777/MicrobiomeStat@HEAD
── R CMD build ───────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\warrenf\AppData\Local\Temp\RtmpAZmkKW\remotes2ed41c6b2a8b\cafferychen777-MicrobiomeStat-4c387fb/DESCRIPTION' (513ms)
─  preparing 'MicrobiomeStat': (7s)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (1.3s)
─  checking for empty or unneeded directories
─  building 'MicrobiomeStat_1.1.3.tar.gz'
   
Installing package into ‘C:/Users/warrenf/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'MicrobiomeStat' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Note: wrong number of arguments to 'sqrt' 
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'MicrobiomeStat' in namespaceExport(ns, exports):
 undefined exports: generate_taxa_latticeplot_single
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/warrenf/AppData/Local/R/win-library/4.2/MicrobiomeStat'

I am not sure what is causing this error, I have installed all fo the dependencies.

Thanks

Fred

**Comment by cafferychen777** [comment]
Hi Fred,

I apologize for the inconvenience. It seems that I accidentally pushed some unfinished code to GitHub, which is causing the installation issue. I am working on resolving this right away. Please give me a moment, and I will update the repository with the correct version. I appreciate your patience and understanding.

Best regards,
Chen YANG
