### ISSUE TITLE
generate_taxa_areaplot_long “No shared levels found between names(values)..."

### ISSUE THREAD

**Issue by srosales712** [cafferychen777/MicrobiomeStat#43]
Hi I'm trying to run the function generate_taxa_areaplot_long and get the below error:

Rule 1 passed: data.obj is a list.

Rule 2 passed: meta.dat is a data.frame.

Rule 3 passed: The row names of feature.tab match the row names of feature.ann.

Rule 4 passed: The column names of feature.tab match the row names of meta.dat.

Rule 5 passed: feature.tab is a matrix.

Rule 6 passed: feature.ann is a matrix.

Please note: The data components should follow base R data.frame and matrix structures, not phyloseq's formal class.

Validation passed.

Note: Passing validation does not guarantee the absence of all data issues. Further data exploration may be needed.

Warning message:
“No shared levels found between `names(values)` of the manual scale and the data's colour
values.”
Warning message:
“No shared levels found between `names(values)` of the manual scale and the data's colour
values.”

```r
ps_to_ms <- mStat_convert_phyloseq_to_data_obj(ps)

generate_taxa_areaplot_long(
  data.obj = ps_to_ms,
  subject.var = "Sample.ID", 
  time.var = "Site_Num",
  group.var = "Site.Status",
  feature.level = "Family",
  feature.dat.type = "proportion",  
  feature.number = 10,
  base.size = 10,
  theme.choice = "bw",
  palette = NULL,
  pdf = TRUE,
  file.ann = NULL
)

```

A  figure is printed with the Family key, but the actual area plot is empty with no taxonomy in the main figure. 

**Screenshots**

<img width="499" alt="Screenshot 2024-04-02 at 1 58 02 PM" src="https://github.com/cafferychen777/MicrobiomeStat/assets/32393432/dad2288a-124c-4b28-b903-8b916a74a2c4">

**Environment Information:**

 - Operating System:
R version 4.3.2 (2023-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Big Sur ... 10.16

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] qiime2R_0.99.6       pivottabler_1.5.5    vegan_2.6-4         
 [4] lattice_0.22-5       permute_0.9-7        lubridate_1.9.3     
 [7] forcats_1.0.0        stringr_1.5.1        dplyr_1.1.4         
[10] purrr_1.0.2          readr_2.1.4          tidyr_1.3.1         
[13] tidyverse_2.0.0      microbiome_1.24.0    phyloseq_1.46.0     
[16] ggplot2_3.5.0        MicrobiomeStat_1.1.3 tibble_3.2.1        
[19] rlang_1.1.3         

Any advice is greatly appreciated.

**Comment by cafferychen777** [comment]
Hi @srosales712,

Thank you for reaching out and providing detailed information about the issue you're experiencing with the `generate_taxa_areaplot_long` function in MicrobiomeStat.

From the screenshot you shared, I noticed that each facet (determined by "Site.Status") corresponds to only one timepoint. Is this the intended structure of your data, or could there be an issue with how the data is organized?

If your data is indeed structured this way, with each "Site.Status" corresponding to a single timepoint, I recommend setting the `group.var` argument to `NULL` in the `generate_taxa_areaplot_long` function. This change should allow the function to generate the area plot without grouping by "Site.Status," which might resolve the issue of the empty plot.

Please try this adjustment and let me know if it resolves the problem. If the issue persists, feel free to provide further details, and I'll be happy to assist you further.

Best regards,
Caffery Yang

**Comment by srosales712** [comment]
I set the group.var argument to NULL and that fixed the problem. Thank you for the quick and helpful response!
