### ISSUE TITLE
Unable to install zipped-version

### ISSUE THREAD

**Issue by mariamaseng** [cafferychen777/MicrobiomeStat#5]
Hi,
thank you for your wonderful package. 

I want to install the github version of it inside TSD. I then download the zip file from github, import it into TSD and there install it. However, when I try to install it I get the error message: 

Warning messages:
1. In loadNamespace(package, ..) : package "microbiomeStat" has no "package.rd" in Meta/
2. S3 methods "as.grob.aplot", "is.na.null" were declared in NAMESPACE but not found

Any workaround this?
Thanks again,
Maria

**Comment by cafferychen777** [comment]
Hello @mariamaseng,

Maybe you can try https://github.com/cafferychen777/MicrobiomeStat/releases/tag/MicrobiomeStat_Version_1.1.1

Best regards,

**Comment by mariamaseng** [comment]
Thank you so much! I really appriciate how quilckly you made this possible. It works perfectly!
