### ISSUE TITLE
Parameter Names Incorrect in mStat_import_biom_as_data_obj

### ISSUE THREAD

**Issue by pkirti33** [cafferychen777/MicrobiomeStat#50]
**Documentation Section**
SETTING UP MICROBIOMESTAT: INSTALLATION AND DATA PREPARATION --> Creating the MicrobiomeStat Data Object --> Importing Data from BIOM into MicrobiomeStat
The specific page is [linked here](https://www.microbiomestat.wiki/setting-up-microbiomestat-installation-and-data-preparation/laying-the-foundation-creating-the-microbiomestat-data-object/transferring-data-from-biom-into-microbiomestat).

**Issue with Current Documentation**
On the webpage linked above, the parameter names for the `mStat_import_biom_as_data_obj()` function are listed as `biom_filename` and `tree_filename`. However, in R, they are `BIOMfilename` and `treefilename`.

**Screenshot from R**
![image](https://github.com/cafferychen777/MicrobiomeStat/assets/89867716/f0108f12-eedf-4685-a13c-b07fa4308006)

**Comment by cafferychen777** [comment]
Hi pkirti33,

Thank you for catching this error in the documentation and submitting an issue. You are absolutely right that the correct parameter names in the `mStat_import_biom_as_data_obj()` function should be `BIOMfilename` and `treefilename`, not `biom_filename` and `tree_filename` as I had incorrectly written in the code example. 

I apologize for this mistake and any confusion it may have caused. I have now updated the documentation page you linked with the proper parameter names.

Thanks again for bringing this to my attention so I could fix it. Please let me know if you notice any other issues or have additional suggestions for improving the MicrobiomeStat documentation.

Best regards,
Caffery
