### ISSUE TITLE
Zero-handling Doesn't Work if a Sample is All Zero

### ISSUE THREAD

**Issue by DarioS** [cafferychen777/MicrobiomeStat#53]
I have some samples which have zero species of bacteria detected. For example, Oral 2.

```r
Browse[1]> Y[1:5, 1:5]
                          Oral_1-N Oral_2-N Oral_3-N Oral_4-N Oral_5-N
Fusobacterium nucleatum       0.00        0    0.038    0.000     0.00
Cutibacterium acnes           0.00        0    0.113    0.102     0.69
Prevotella melaninogenica     0.00        0    0.000    0.000     0.00
Streptococcus mitis           0.67        0    0.000    0.013     0.20
Prevotella intermedia         0.00        0    0.000    0.000     0.00
```

The line `temp <- t(t(Y) / colSums(Y))` causes problems soon after.

```r
NA  features are filtered!
Error in if (any(colSums(Y) == 0)) { : missing value where TRUE/FALSE needed
```

I think it is biologically informative data and I wish to keep such samples for linear modelling. Can LinDA be modified to handle it? Or, should a dummy row named UNCLASSIFIED be present with 1.00 in it for samples without any species?

**Comment by cafferychen777** [comment]
Hi Dario,

Thank you for reporting this issue with LinDA handling samples that have zero detected bacterial species. 

To investigate further, would you be able to share the full dataset with me? I haven't encountered this type of problem before and would like to test it out. You can send the data to my email at cafferychen777@tamu.edu.

Please send over the dataset when you have a chance. I appreciate you bringing this to my attention and look forward to working on a fix.

Best regards,
Caffery

**Comment by DarioS** [comment]
It is shared.

**Comment by cafferychen777** [comment]
Dear Dario,

Thank you for your question and for bringing this issue to our attention. 

Regarding the problem you encountered with samples having all zero reads, such as the "Oral_2-N" sample in your example, I agree that it is best to remove such samples from the analysis. The presence of samples with all zero reads suggests that there might be issues with the upstream processing of these samples, such as problems during sample preparation, sequencing, or data processing.

Including these problematic samples in the linear modeling is unlikely to provide any meaningful biological information. In fact, attempting to retain them may introduce errors and biases into the analysis, potentially leading to incorrect conclusions.

Therefore, I recommend filtering out any samples that have all zero reads across all taxa before proceeding with the linear modeling. This can be done as a pre-processing step to ensure that only samples with valid and informative data are included in the analysis.

If you have any further questions or need assistance with modifying the LinDA pipeline to handle this filtering step, please let me know. I'll be happy to provide guidance or make the necessary changes in the code.

Thank you for using MicrobiomeStat and for your valuable feedback. We appreciate your effort in identifying and reporting this issue.

Best regards,
Chen YANG

**Comment by DarioS** [comment]
It could also be that some cancer samples (or different regions within a sample) have bacteria but others do not have any.

![image](https://github.com/cafferychen777/MicrobiomeStat/assets/631218/39f5ca95-d96e-4d73-8fad-7e14abee6036)

**Comment by jchen1981** [comment]
If this is the case, I will recommend that you first compare the
detection rate between groups. After that, you can then focus on the
samples with bacteria detection.  We usually first filter samples with
extreme low depth as a quality control step. These samples could have some
technical issues in preparation and sequencing.
